New Makefile and build workflow update

diff --git a/.github/workflows/buildService.yml b/.github/workflows/buildService.yml
--- a/.github/workflows/buildService.yml
+++ b/.github/workflows/buildService.yml
@@ -18,37 +18,37 @@ jobs:
 
       - name: Checkout services repository
         uses: actions/checkout@v4
-      
+
       - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
+        uses: docker/setup-buildx-action@v3
         with:
           install: true
-      
-      - name: Verify Docker installation
-        run: |
-          # Check if Docker is installed and in PATH
-          if ! command -v docker &> /dev/null; then
-            echo "Docker not found in PATH. Attempting to locate and add to PATH..."
-            DOCKER_PATH=$(sudo find / -name docker -type f -executable 2>/dev/null | head -n 1)
-            if [ -n "$DOCKER_PATH" ]; then
-              echo "Found Docker at $DOCKER_PATH"
-              echo "$(dirname $DOCKER_PATH)" >> $GITHUB_PATH
-              echo "Added Docker directory to PATH"
-            else
-              echo "Docker executable not found. Please ensure Docker is installed."
-              exit 1
-            fi
-          else
-            echo "Docker is already in PATH"
-          fi
-          # Verify Docker is now accessible
-          docker --version
-          docker info
-      
-      - name: Setup binfmt
-        run: |
-          docker run --privileged --rm tonistiigi/binfmt --install all
-      
+
+      # - name: Verify Docker installation
+      #   run: |
+      #     # Check if Docker is installed and in PATH
+      #     if ! command -v docker &> /dev/null; then
+      #       echo "Docker not found in PATH. Attempting to locate and add to PATH..."
+      #       DOCKER_PATH=$(sudo find / -name docker -type f -executable 2>/dev/null | head -n 1)
+      #       if [ -n "$DOCKER_PATH" ]; then
+      #         echo "Found Docker at $DOCKER_PATH"
+      #         echo "$(dirname $DOCKER_PATH)" >> $GITHUB_PATH
+      #         echo "Added Docker directory to PATH"
+      #       else
+      #         echo "Docker executable not found. Please ensure Docker is installed."
+      #         exit 1
+      #       fi
+      #     else
+      #       echo "Docker is already in PATH"
+      #     fi
+      #     # Verify Docker is now accessible
+      #     docker --version
+      #     docker info
+
+      # - name: Setup binfmt
+      #   run: |
+      #     docker run --privileged --rm tonistiigi/binfmt --install all
+
       - name: Build the service package
         id: build
         run: |
